artifacts_root: artifacts

image_ingestion:
  root_dir: artifacts/image_ingestion
  database_path: artifacts/image_ingestion/database
  image_dir: data/images/
  known_people_data: data/known_people.yaml